# Generated by Django 4.2.6 on 2023-11-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackandtrace', '0002_profile_master_key_profile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
